- title: Register
  icon: '/illustrations/fill-form.svg'
  description: Register for free & put up your Profile
- title: Match from Professionals
  icon: '/illustrations/match.svg'
  description: Professionals will analyze your profile and find a perfect match for you
- title: Meet the match
  icon: '/illustrations/meeting.svg'
  description: Meet your match and the professional
- title: Marry
  icon: '/illustrations/marriage.svg'
  description: Get married with Merobiha.com guarantee
